In [1]:
import numpy as np


In [4]:
a = np.array([1, 2, 3, 4, 5])
print("1D array:")
print(a)
print("Shape of a:", a.shape)
print("Data type of a:", a.dtype)
print("Number of dimensions of a:", a.ndim)
print("Size of a:", a.size)

1D array:
[1 2 3 4 5]
Shape of a: (5,)
Data type of a: int64
Number of dimensions of a: 1
Size of a: 5


In [5]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:")
print(b)
print("Shape of b:", b.shape)
print("Data type of b:", b.dtype)
print("Number of dimensions of b:", b.ndim)
print("Size of b:", b.size)

2D array:
[[1 2 3]
 [4 5 6]]
Shape of b: (2, 3)
Data type of b: int64
Number of dimensions of b: 2
Size of b: 6


In [6]:
# 3D array  
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:")
print("Shape of c:", c.shape)
print("Data type of c:", c.dtype)
print("Number of dimensions of c:", c.ndim)
print("Size of c:", c.size)
print(c)

3D array:
Shape of c: (2, 2, 2)
Data type of c: int64
Number of dimensions of c: 3
Size of c: 8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# Array creation
d = np.zeros((2, 3))
print("Array of zeros:")
print(d)
e = np.ones((3, 4))
print("Array of ones:")
print(e)
f = np.full((2, 2), 7)  
print("Array filled with 7:")
print(f)
g = np.eye(4)
print("Identity matrix:")
print(g)
h = np.random.rand(2, 3)
print("Random array:")
print(h)
h1 = np.random.uniform(low=0, high=10, size=(2, 3))
print("Random array with uniform distribution:")
print(h1)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array filled with 7:
[[7 7]
 [7 7]]
Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random array:
[[0.85863366 0.08637    0.15659679]
 [0.53531277 0.8104399  0.95443942]]
Random array with uniform distribution:
[[5.50783446 4.47629696 9.32191789]
 [7.9978342  9.72172612 6.12455203]]


In [8]:
# Array operations
i = np.array([1, 2, 3])
j = np.array([4, 5, 6])
print("Element-wise addition:")
print(i + j)
print("Element-wise multiplication:")
print(i * j)
print("Dot product:")
print(np.dot(i, j))
print("Transpose of a 2D array:")
k = np.array([[1, 2], [3, 4]])
print(k.T)

Element-wise addition:
[5 7 9]
Element-wise multiplication:
[ 4 10 18]
Dot product:
32
Transpose of a 2D array:
[[1 3]
 [2 4]]


In [9]:
# Array slicing and indexing
l = np.array([10, 20, 30, 40, 50])
print("Slicing from index 1 to 3:")
print(l[1:4])
print("Slicing with step of 2:")
print(l[::2])
print("Negative indexing:")
print(l[-2:])
print("Boolean indexing:")
m = np.array([1, 2, 3, 4, 5])
print("Elements greater than 3:")
print(m[m > 3])

Slicing from index 1 to 3:
[20 30 40]
Slicing with step of 2:
[10 30 50]
Negative indexing:
[40 50]
Boolean indexing:
Elements greater than 3:
[4 5]


In [10]:
# Reshaping and flattening
n = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(n)
print("Reshaped array (3, 2):")
print(n.reshape(3, 2))
print("Flattened array:")
print(n.flatten())

Original array:
[[1 2 3]
 [4 5 6]]
Reshaped array (3, 2):
[[1 2]
 [3 4]
 [5 6]]
Flattened array:
[1 2 3 4 5 6]


In [11]:
# Statistical operations
o = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(o))
print("Median:", np.median(o))  
print("Standard deviation:", np.std(o))
print("Variance:", np.var(o))



Mean: 3.0
Median: 3.0
Standard deviation: 1.4142135623730951
Variance: 2.0


In [13]:
# Broadcasting: Adding a 1D array to a 2D array, where the 1D array is broadcasted across the rows of the 2D array.
p = np.array([1, 2, 3])
q = np.array([[1], [2], [3]])
print("Original arrays:")
print("p:", p)
print("q:\n", q)
print("Broadcasted addition:")
print(p + q)


Original arrays:
p: [1 2 3]
q:
 [[1]
 [2]
 [3]]
Broadcasted addition:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [16]:
%pip install pillow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
# Image as a 2D array (grayscale) and 3D array (color)
r = np.array([[0, 255], [255, 0]])
print("Grayscale image as a 2D array:")
print(r)

# Color image as a 3D array (RGB)
color_image = np.array([[[255, 0, 0], [0, 255, 0]], [[0, 0, 255], [255, 255, 0]]])
print("Color image as a 3D array:")
print(color_image)

Grayscale image as a 2D array:
[[  0 255]
 [255   0]]
Color image as a 3D array:
[[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255   0]]]


In [21]:
# Read image using PIL and convert to NumPy array
from PIL import Image
try:
    img = Image.open('images.jpeg')  # Replace with your image path
    img_array = np.array(img)
    print("Image as a NumPy array:")
    print(img_array)
    print("Shape of the image array:", img_array.shape)
    print("Data type of the image array:", img_array.dtype)
    print("Number of dimensions of the image array:", img_array.ndim)
    print("Size of the image array:", img_array.size)

    # Invert the colors of the image
    inverted_img_array = 255 - img_array
    inverted_img = Image.fromarray(inverted_img_array)
    inverted_img.save('inverted_image.jpeg')  # Save the inverted image

    # Convert the image to grayscale
    grayscale_img = img.convert('L')
    grayscale_img.save('grayscale_image.jpeg')  # Save the grayscale image
except FileNotFoundError:
    print("Image file not found. Please check the path and try again.")



Image as a NumPy array:
[[[250 250 250]
  [237 237 237]
  [239 239 239]
  ...
  [255 255 255]
  [255 255 255]
  [247 247 247]]

 [[248 248 248]
  [236 236 236]
  [236 236 236]
  ...
  [252 252 252]
  [255 255 255]
  [248 248 248]]

 [[245 245 245]
  [235 235 235]
  [233 233 233]
  ...
  [252 252 252]
  [255 255 255]
  [249 249 249]]

 ...

 [[239 239 239]
  [255 255 255]
  [255 255 255]
  ...
  [242 242 242]
  [235 235 235]
  [240 240 240]]

 [[240 240 240]
  [255 255 255]
  [255 255 255]
  ...
  [238 238 238]
  [230 230 230]
  [243 243 243]]

 [[239 239 239]
  [255 255 255]
  [255 255 255]
  ...
  [237 237 237]
  [231 231 231]
  [241 241 241]]]
Shape of the image array: (225, 225, 3)
Data type of the image array: uint8
Number of dimensions of the image array: 3
Size of the image array: 151875


In [22]:
%pip install scipy

  Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [26]:
# Kernel or Filter application
# Applying a simple edge detection kernel to a given image using PIL and SciPy (if available)
try:
    from scipy import ndimage
    # Define a simple edge detection kernel (Sobel operator)
    kernel = np.array([[-1, 0, 1],
                       [-2, 0, 2],
                       [-1, 0, 1]], dtype=np.float32)

    # Reuse existing grayscale_array if available; otherwise create it
    if 'grayscale_array' not in globals():
        img = Image.open('images.jpeg')  # Replace with your image path
        grayscale_img = img.convert('L')
        grayscale_array = np.array(grayscale_img)

    # Apply the 2D kernel to the 2D grayscale image
    edges = ndimage.convolve(grayscale_array.astype(np.float32), kernel, mode='reflect')
    edges = np.clip(np.abs(edges), 0, 255).astype(np.uint8)
    
    # Save the edge-detected image
    edges_img = Image.fromarray(edges)
    edges_img.save('edges_image.jpeg')
except ImportError:
    print("Scipy is not installed. Please install it to use the edge detection feature.")
except FileNotFoundError:
    print("Image file not found. Please check the path and try again.")
